---
title: "Data preparation"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---

```{r eval=FALSE, include=FALSE}
rmarkdown::render(input = "production/prod_data-prep.Rmd",output_format = "html_document",output_dir = "production/");browseURL(url = "production/prod_data-prep.html")
```

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE,results = "hold")
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
```

**libraries**
```{r}
# install.packages("dataverse")
pacman::p_load(dataverse,dplyr,sjlabelled,sjPlot,stargazer,lme4,psych,here)
```

**download data from dataverse**
```{r}
Sys.setenv("DATAVERSE_SERVER" = "dataverse.harvard.edu")
```

```{r eval=FALSE, include=FALSE}
get_dataset(dataset = "https://doi.org/10.7910/DVN/0KIRBJ")
writeBin(get_file(file    = "ELSOC_W01_v3.10_R.tab", #Descarga y guardado local en .RData
                  dataset = "https://doi.org/10.7910/DVN/0KIRBJ"),
         "input/data/original/ELSOC_W01_v3.10.RData")
```

```{r eval=FALSE, include=FALSE}
get_dataset(dataset = "https://doi.org/10.7910/DVN/JDJLPQ")

writeBin(get_file(file    = "ELSOC_W02_v2.10_R.tab", #Descarga y guardado local en .RData
                  dataset = "https://doi.org/10.7910/DVN/JDJLPQ"), 
         "input/data/original/ELSOC_W02_v2.10_R.RData")
```

```{r eval=FALSE, include=FALSE}
get_dataset(dataset = "https://doi.org/10.7910/DVN/H8OVMF")
writeBin(get_file(file    = "ELSOC_W03_v1.10_Stata14.tab", #Descarga y guardado local en .RData
                  dataset = "https://doi.org/10.7910/DVN/H8OVMF"), 
         "input/data/original/ELSOC_W03.dta")
```

**load data**

```{r}
load("input/data/original/ELSOC_W01_v3.10.RData");   elsoc16<- elsoc_2016; remove(elsoc_2016)
load("input/data/original/ELSOC_W02_v2.10_R.RData"); elsoc17<- elsoc_2017; remove(elsoc_2017)
read_stata(path = "input/data/original/ELSOC_W03.dta") -> elsoc18
load("input/data/original/ELSOC_W04_v1.00_R.RData"); elsoc19<- elsoc_2019; remove(elsoc_2019)
```

# Datos wide

## wave 2016

```{r}
elsoc16[elsoc16==-999] <- NA
elsoc16[elsoc16==-888] <- NA
w01 <- elsoc16 %>% select(idencuesta,
                          "mujer"=m0_sexo,
                          "edad"=m0_edad,
                          "educacion"=m01,
                          "income_range"=m30,
                          "income_num"=m29,    
                          "n_hogar"=nhogar1,
                          "edpadre"=m27,
                          "edmadre"=m28,
                          "ess"=d01_01,
                          "essfam"=d01_02,
                          # "justpens" = d02_01,
                          # "justeduc" = d02_02,
                          # "justsalud" = d02_03,
                          # "mesfuerzo"= c18_09,
                          # "mtalento" = c18_10,
                          "salperger"= d03_01,
                          "salperobr"= d03_02,
                          "saljusobr"= d04_02 ,
                          "saljusger"= d04_01) %>% 
  mutate(salperobr=replace(salperobr, salperobr <= 40000  | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000  | saljusobr>=999999999999999, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000 | saljusger>=999999999999999, NA)) %>% 
  mutate(movsubj = as.numeric(ess - essfam)) %>%
  mutate(mov_sub_c= case_when(
    movsubj  > 0 ~ "Mov. Asc.",
    movsubj == 0 ~ "Estable",
    movsubj  < 0 ~ "Mov. Des.",
  )) %>% 
  mutate(mov_sub_c = factor(mov_sub_c))


# Educacion encuestado en years
w01$educacion_n <-  car::recode(w01$educacion,
            "1=0;2=4.3;3=7.5;4=9.8;5=12.02;6=13.9;7=14.8;8=14.9;9=16.9;10=19.07;c(-888,-999)=NA", as.numeric = T)
class(w01$educacion_n);summary(w01$educacion_n)

# Educacion PADRE en years
w01$edpadre_n <-  car::recode(w01$edpadre,
            "1=0;2=4.3;3=7.5;4=9.8;5=12.02;6=13.9;7=14.8;8=14.9;9=16.9;10=19.07;c(-888,-999)=NA", as.numeric = T)
class(w01$edpadre); summary(w01$edpadre)

# Educacion MADRE en years
w01$edmadre_n <-  car::recode(w01$edmadre,
            "1=0;2=4.3;3=7.5;4=9.8;5=12.02;6=13.9;7=14.8;8=14.9;9=16.9;10=19.07;c(-888,-999)=NA", as.numeric = T)
class(w01$edmadre_n);summary(w01$edmadre_n)

# Educacion PADRE, remplazar por MADRE en years
w01$edparent_n <- ifelse(test=is.na(w01$edpadre_n),yes = w01$edmadre_n,no = w01$edpadre_n) 
class(w01$edparent_n);summary(w01$edparent_n)

# Movilidad educacional encuestado - padres
w01$moveduc <- as.numeric(w01$educacion_n-w01$edparent_n) 
sjmisc::frq(w01$moveduc)

# Movilidad educativa categorica
w01 <- w01 %>% 
mutate(mov_educ_c= case_when(
    moveduc  > 0 ~ "Mov. Asc.",
    moveduc == 0 ~ "Estable",
    moveduc  < 0 ~ "Mov. Des.",
  ))

sjmisc::frq(w01$mov_educ_c)
w01$mov_educ_c <- factor(w01$mov_educ_c,
                         levels = c("Estable","Mov. Asc.","Mov. Des."),
                         labels = c("Estable","Mov. Asc.","Mov. Des."))
sjmisc::frq(w01$mov_educ_c)
# income recode________________________________________________________________
sjmisc::frq(w01$income_range) #check income categorical
#inputation of the mean value of the income range
w01$income_range_r <- 
  as.numeric(car::recode(
    var = w01$income_range,
    recodes = c(
      "1=110000;2=251000;3=305000;4=355000;5=400000;6=445000;7=490000;8=535000;
      9=585000;10=640000;11=700000;12=765000;13=845000;14=935000;15=1040000;
      16=1180000;17=1375000;18=1670000;19=2275000;20=2700000"
      )))
sjmisc::frq(w01$income_range_r) #check
summary(w01$income_num) #income unmerical
#replace missing values in income numerical by the mean value of the categorial
w01$income_num_r <- ifelse(is.na(w01$income_num),yes = w01$income_range_r,no = w01$income_num)   
summary(w01$income_num_r)  

# household income per capita
summary(w01$n_hogar)
w01$income_pc <- (w01$income_num_r/w01$n_hogar)
summary(w01$income_pc)

# create percap income quintile 

w01$inc05 <- ntile(w01$income_pc, 5)
w01$inc05 <- factor(w01$inc05,
                    levels = 1:5,labels = c("Q01","Q02","Q03","Q04","Q05"))  
sjmisc::frq(w01$inc05)

# median vote distance_________________________________________________________
w01$inc_median <- median(w01$income_pc,na.rm=T) - w01$income_pc
summary(w01$inc_median)

w01$inc_median_eci <- 350000 - w01$income_pc
summary(w01$inc_median_eci)

#---Brecha salarial percibida
w01$gap_perc   <-  as.numeric(w01$salperger/w01$salperobr) # diferencia total
w01$lngap_perc <-  as.numeric(log(w01$gap_perc))                 # diferencia log

#---Brecha salarial justa
w01$gap_just   <-  as.numeric(w01$saljusger/w01$saljusobr) # diferencia total
w01$lngap_just <-  as.numeric(log(w01$gap_just))           # diferencia log
# meritocracia promedio
# w01$pmerit <- as.numeric((w01$mesfuerzo+w01$mtalento)/2)
```

## wave 2017

```{r}
elsoc17[elsoc17==-999] <- NA
elsoc17[elsoc17==-888] <- NA
w02 <- elsoc17 %>% select(idencuesta,
                          "mujer"=m0_sexo,
                          "edad"=m0_edad,
                          "educacion"=m01,
                          "income_range"=m30,
                          "income_num"=m29,      
                          "n_hogar"=m46_nhogar,
                          "ess"=d01_01,
                          "essfam"=d01_02,
                          # "justpens" = d02_01,
                          # "justeduc" = d02_02,
                          # "justsalud"= d02_03,
                          # "mesfuerzo"=c18_09,
                          # "mtalento" =c18_10,
                          "salperger"= d03_01,
                          "salperobr"= d03_02,
                          "saljusobr"= d04_02 ,
                          "saljusger"= d04_01) %>% 
  mutate(salperobr=replace(salperobr, salperobr <= 40000  | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000  | saljusobr>=999999999999999, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000 | saljusger>=999999999999999, NA)) %>% 
  mutate(movsubj = as.numeric(ess - essfam)) %>% 
  mutate(mov_sub_c= case_when(
    movsubj  > 0 ~ "Mov. Asc.",
    movsubj == 0 ~ "Estable",
    movsubj  < 0 ~ "Mov. Des.",
  )) %>% 
  mutate(mov_sub_c = factor(mov_sub_c))

# income recode________________________________________________________________
sjmisc::frq(w02$income_range) #check income categorical
#inputation of the mean value of the income range
w02$income_range_r <- 
  as.numeric(car::recode(
    var = w02$income_range,
    recodes = c(
      "1=110000;2=251000;3=305000;4=355000;5=400000;6=445000;7=490000;8=535000;
      9=585000;10=640000;11=700000;12=765000;13=845000;14=935000;15=1040000;
      16=1180000;17=1375000;18=1670000;19=2275000;20=2700000"
      )))
sjmisc::frq(w02$income_range_r) #check
summary(w02$income_num) #income unmerical
#replace missing values in income numerical by the mean value of the categorial
w02$income_num_r <- ifelse(is.na(w02$income_num),yes = w02$income_range_r,no = w02$income_num)   
summary(w02$income_num_r)  

# household income per capita
summary(w02$n_hogar)
w02$income_pc <- (w02$income_num_r/w02$n_hogar)
summary(w02$income_pc)

# create percap income quintile 

w02$inc05 <- ntile(w02$income_pc, 5)
w02$inc05 <- factor(w02$inc05,
                    levels = 1:5,labels = c("Q01","Q02","Q03","Q04","Q05"))  

sjmisc::frq(w02$inc05) 
# median vote distance_________________________________________________________
w02$inc_median <- median(w02$income_pc,na.rm=T) - w02$income_pc
summary(w02$inc_median)

#median is from the Encuesta suplementaria de Ingresos
w02$inc_median_eci <- 380000 - w02$income_pc
summary(w02$inc_median_eci)

#---Brecha salarial percibida
w02$gap_perc   <-  as.numeric(w02$salperger/w02$salperobr) # diferencia total
w02$lngap_perc <-  as.numeric(log(w02$gap_perc))                 # diferencia log

#---Brecha salarial justa
w02$gap_just   <-  as.numeric(w02$saljusger/w02$saljusobr) # diferencia total
w02$lngap_just <-  as.numeric(log(w02$gap_just))                # diferencia log
# meritocracia promedio
# w02$pmerit <- as.numeric((w02$mesfuerzo+w02$mtalento)/2)
```

## wave 2018

```{r}
elsoc18[elsoc18==-999] <- NA
elsoc18[elsoc18==-888] <- NA
w03 <- elsoc18 %>% select(idencuesta,
                          "mujer"=m0_sexo,
                          "edad"=m0_edad,
                          "educacion"=m01,
                          "income_range"=m30,
                          "income_num"=m29,  
                          "n_hogar"=m54,
                          "ess"=d01_01,
                          "essfam"=d01_02,
                          "justpens" = d02_01,
                          "justeduc" = d02_02,
                          "justsalud"= d02_01,
                          # "mesfuerzo"= c18_09,
                          # "mtalento" = c18_10,
                          "salperger"= d03_01,
                          "salperobr"= d03_02,
                          "saljusobr"= d04_02 ,
                          "saljusger"= d04_01) %>% 
  mutate(salperobr=replace(salperobr, salperobr <= 40000  | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000  | saljusobr>=999999999999999, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000 | saljusger>=999999999999999, NA)) %>% 
  mutate(movsubj = as.numeric(ess - essfam)) %>% 
  mutate(mov_sub_c= case_when(
    movsubj  > 0 ~ "Mov. Asc.",
    movsubj == 0 ~ "Estable",
    movsubj  < 0 ~ "Mov. Des.",
  )) %>% 
  mutate(mov_sub_c = factor(mov_sub_c))

# income recode________________________________________________________________
sjmisc::frq(w03$income_range) #check income categorical
#inputation of the mean value of the income range
w03$income_range_r <- 
  as.numeric(car::recode(
    var = w03$income_range,
    recodes = c(
      "1=110000;2=251000;3=305000;4=355000;5=400000;6=445000;7=490000;8=535000;
      9=585000;10=640000;11=700000;12=765000;13=845000;14=935000;15=1040000;
      16=1180000;17=1375000;18=1670000;19=2275000;20=2700000"
      )))
sjmisc::frq(w03$income_range_r) #check
summary(w03$income_num) #income unmerical
#replace missing values in income numerical by the mean value of the categorial
w03$income_num_r <- ifelse(is.na(w03$income_num),yes = w03$income_range_r,no = w03$income_num)   
summary(w03$income_num_r)  

# household income per capita
summary(w03$n_hogar)
w03$income_pc <- (w03$income_num_r/w03$n_hogar)
summary(w03$income_pc)

# create percap income quintile 

w03$inc05 <- ntile(w03$income_pc, 5)
w03$inc05 <- factor(w03$inc05,
                    levels = 1:5,labels = c("Q01","Q02","Q03","Q04","Q05"))  
sjmisc::frq(w03$inc05)  
# median vote distance_________________________________________________________
w03$inc_median <- median(w03$income_pc,na.rm=T) - w03$income_pc
summary(w03$inc_median)

#median is from the Encuesta suplementaria de Ingresos
w03$inc_median_eci <- 400000 - w03$income_pc
summary(w03$inc_median_eci)
  
#---Brecha salarial percibida
w03$gap_perc   <-  as.numeric(w03$salperger/w03$salperobr) # diferencia total
w03$lngap_perc <-  as.numeric(log(w03$gap_perc))                 # diferencia log

#---Brecha salarial justa
w03$gap_just   <-  as.numeric(w03$saljusger/w03$saljusobr) # diferencia total
w03$lngap_just <-  as.numeric(log(w03$gap_just))           # diferencia log
# meritocracia promedio
# w03$pmerit <- as.numeric((w03$mesfuerzo+w03$mtalento)/2)
```

## wave 2019

```{r}
elsoc19[elsoc19==-999] <- NA
elsoc19[elsoc19==-888] <- NA
w04 <- elsoc19 %>% select(idencuesta,
                          "mujer"=m0_sexo,
                          "edad"=m0_edad,
                          "ess"=d01_01,
                          "essfam"=d01_02,
                          "educacion"=m01,
                          "income_range"=m30,
                          "income_num"=m29,
                          "n_hogar"=m54,
                          # "justpens" = d02_01,
                          # "justeduc" = d02_02,
                          # "justsalud"= d02_01,
                          # "mesfuerzo"= c18_09,
                          # "mtalento" = c18_10,
                          "salperger"= d03_01,
                          "salperobr"= d03_02,
                          "saljusobr"= d04_02 ,
                          "saljusger"= d04_01) %>% 
  mutate(salperobr=replace(salperobr, salperobr <= 40000  | salperobr>= 1000000, NA)) %>%
  mutate(salperger=replace(salperger, salperger <= 250000 | salperger>= 100000001, NA)) %>%
  mutate(saljusobr=replace(saljusobr, saljusobr <= 40000  | saljusobr>=999999999999999, NA)) %>%
  mutate(saljusger=replace(saljusger, saljusger <= 100000 | saljusger>=999999999999999, NA)) %>% 
  mutate(movsubj = as.numeric(ess - essfam)) %>%
  mutate(mov_sub_c= case_when(
    movsubj  > 0 ~ "Mov. Asc.",
    movsubj == 0 ~ "Estable",
    movsubj  < 0 ~ "Mov. Des.",
  )) %>% 
  mutate(mov_sub_c = factor(mov_sub_c))


# income recode________________________________________________________________
sjmisc::frq(w04$income_range) #check income categorical
#inputation of the mean value of the income range
w04$income_range_r <- 
  as.numeric(car::recode(
    var = w04$income_range,
    recodes = c(
      "1=110000;2=251000;3=305000;4=355000;5=400000;6=445000;7=490000;8=535000;
      9=585000;10=640000;11=700000;12=765000;13=845000;14=935000;15=1040000;
      16=1180000;17=1375000;18=1670000;19=2275000;20=2700000"
      )))
sjmisc::frq(w04$income_range_r) #check
summary(w04$income_num) #income unmerical
#replace missing values in income numerical by the mean value of the categorial
w04$income_num_r <- ifelse(is.na(w04$income_num),yes = w04$income_range_r,no = w04$income_num)   
summary(w04$income_num_r)  

# household income per capita
summary(w04$n_hogar)
w04$income_pc <- (w04$income_num_r/w04$n_hogar)
summary(w04$income_pc)

# create percap income quintile 

w04$inc05 <- ntile(w04$income_pc, 5)
w04$inc05 <- factor(w04$inc05,
                    levels = 1:5,labels = c("Q01","Q02","Q03","Q04","Q05"))  
sjmisc::frq(w04$inc05)  

# median vote distance_________________________________________________________
w04$inc_median <- median(w04$income_pc,na.rm=T) - w04$income_pc
summary(w04$inc_median)

#median is from the Encuesta suplementaria de Ingresos
w04$inc_median_eci <- 401000 - w04$income_pc
summary(w04$inc_median_eci)

#---Brecha salarial percibida
w04$gap_perc   <-  as.numeric(w04$salperger/w04$salperobr) # diferencia total
w04$lngap_perc <-  as.numeric(log(w04$gap_perc))                 # diferencia log

#---Brecha salarial justa
w04$gap_just   <-  as.numeric(w04$saljusger/w04$saljusobr) # diferencia total
w04$lngap_just <-  as.numeric(log(w04$gap_just))           # diferencia log
# meritocracia promedio
# w04$pmerit <- as.numeric((w04$mesfuerzo+w04$mtalento)/2)
```

## Merge data

```{r}
wide_a<- w01 %>% 
  left_join(w02,"idencuesta", suffix = c(".w1", ".w2")) 

wide_b <- w03 %>% 
  left_join(w04,"idencuesta", suffix = c(".w3", ".w4")) 
   
wide01 <-  wide_a %>% left_join(wide_b,"idencuesta")

wide01_fix <- 
  wide01 %>% 
  select(idencuesta,
         everything()) %>%
  #fijar a T4
  filter(idencuesta %in% w04$idencuesta) %>% 
  mutate(mujer.w2=mujer.w1,
         mujer.w3=mujer.w1,
         mujer.w4=mujer.w1,
         edad.w2=edad.w1,
         edad.w3=edad.w1,
         edad.w4=edad.w1,
         moveduc.w1=moveduc,
         moveduc.w2=moveduc,
         moveduc.w3=moveduc,
         moveduc.w4=moveduc,
         mov_educat.w1=mov_educ_c,
         mov_educat.w2=mov_educ_c,
         mov_educat.w3=mov_educ_c,
         mov_educat.w4=mov_educ_c)
```

**save data**
```{r}
wide01 <- sjlabelled::drop_labels(wide01,drop.na = T)
view_df(wide01, show.frq = T, show.prc = T,show.type = T)
save(wide01,file = "input/data/proc/wide01.RData")
```

# Base long

* Base sin listwise

```{r}
library(datasets)
library(data.table)
wide01 <- setDT(wide01_fix)
names(wide01)

# fix income to t1
wide01$mov_income.w1 <- as.numeric(wide01$income_pc.w4-wide01$income_pc.w1)
wide01$mov_income.w2 <- wide01$mov_income.w1
wide01$mov_income.w3 <- wide01$mov_income.w1
wide01$mov_income.w4 <- wide01$mov_income.w1

# sjmisc::frq(wide01$mov_income)
wide01$mov_median_inc.w1 <- as.numeric(wide01$inc_median.w4-wide01$inc_median.w1)
wide01$mov_median_inc.w2 <- wide01$mov_median_inc.w1
wide01$mov_median_inc.w3 <- wide01$mov_median_inc.w1
wide01$mov_median_inc.w4 <- wide01$mov_median_inc.w1

# sjmisc::frq(as.numeric(wide01$inc05.w4))
# sjmisc::frq(wide01$inc05.w4)
wide01$mov_inc05.w1 <- as.numeric(as.numeric(wide01$inc05.w4)-as.numeric(wide01$inc05.w1))
wide01$mov_inc05.w2 <- wide01$mov_inc05.w1
wide01$mov_inc05.w3 <- wide01$mov_inc05.w1
wide01$mov_inc05.w4 <- wide01$mov_inc05.w1
sjmisc::frq(wide01$mov_inc05.w1); sjPlot::plot_frq(wide01$mov_inc05.w1)

wide01$mov_ess.w1 <- as.numeric(wide01$ess.w4-wide01$ess.w1)
wide01$mov_ess.w2 <- wide01$mov_ess.w1
wide01$mov_ess.w3 <- wide01$mov_ess.w1
wide01$mov_ess.w4 <- wide01$mov_ess.w1
sjmisc::frq(wide01$mov_ess.w1); sjPlot::plot_frq(wide01$mov_ess.w1)

long01<- melt(wide01, id.vars = "idencuesta",
              variable.name = "year",
              measure = patterns("^mujer.","^edad.","^educacion.","^ess.","^essfam.",
                                 "^movsubj.","^mov_sub_c.","^moveduc.",
                                 "^income_pc.","^inc05.","^mov_income.","^mov_inc05",
                                 "^mov_median_inc.","^mov_ess.","^mov_educat.",
                                 "^salperger.","^salperobr","^saljusobr.","^saljusger.",
                                 "^gap_perc.","^lngap_perc.","^gap_just.","^lngap_just."),
              value.name = c("mujer","edad","educacion","ess","essfam",
                             "movsubj","mov_sub_c","moveduc",
                             "income_pc","inc05", "mov_income","mov_inc05",
                             "mov_median_inc", "mov_ess","mov_educat",
                             "salperger","salperobr","saljusobr","saljusger",
                             "gap_perc","lngap_perc","gap_just","lngap_just"),
              value.factor = T)

# sjmisc::frq(long01$mov_median_inc)
# sjmisc::frq(long01$mov_inc05)
# sjmisc::frq(long01$mov_educ)
# sjmisc::frq(long01$movsubj)
# sjmisc::frq(long01$mov_sub_c)
#centrado movilidad subjetiva
long01 <- long01 %>% group_by(idencuesta) %>% mutate(mov_subj_mean = mean(movsubj,na.rm=T))
long01$mov_subj_cwc<-long01$movsubj - long01$mov_subj_mean

#centrado movilidad subjetiva categorica
long01$sub_asc<-as.integer(car::recode(long01$mov_sub_c, "'Mov. Asc.'=1;c('Mov. Des.','Estable')=0"))
long01$sub_des<-as.integer(car::recode(long01$mov_sub_c, "'Mov. Des.'=1;c('Mov. Asc.','Estable')=0"))
sjmisc::frq(long01$sub_asc)
sjmisc::frq(long01$sub_des)

long01 <- long01 %>% group_by(idencuesta) %>% mutate(sub_asc_cgm = mean(sub_asc,na.rm=T))

long01$sub_asc_cwc<-long01$sub_asc-long01$sub_asc_cgm
summary(long01$sub_asc_cwc)

long01 <- long01 %>% group_by(idencuesta) %>% mutate(sub_des_cgm = mean(sub_des,na.rm=T))
long01$sub_des_cwc<-long01$sub_des-long01$sub_des_cgm
summary(long01$sub_des_cwc)

# recode year__________________________________________________________________
long01$year <- car::recode(long01$year,recodes = "1=2016;2=2017;3=2018;4=2019")
long01a <- long01
dim(long01a)
long01a <- long01a %>% filter(year %in% c(2016,2017,2018,2019))
long01a$year <- factor(long01a$year,
                       levels = c(2016,2017,2018,2019),
                       labels = c("2016","2017","2018","2019"))


# obtain id values______________________________________________________________
na_long <- na.omit(long01a)
ids <- 
  sjmisc::frq(na_long$idencuesta) %>% 
  data.frame() %>% 
  filter(frq >=3)
ids_filter <- ids$val

view_df(long01a,show.type = T)

# save data___________________________________________________________________
save(long01a,file = "input/data/proc/long01a.RData")
```

* Base fija wave 4 

```{r}
library(datasets)
library(data.table)
wide01 <- setDT(wide01_fix)
names(wide01)

wide01$mov_income.w1 <- as.numeric(wide01$income_pc.w4-wide01$income_pc.w1)
wide01$mov_income.w2 <- wide01$mov_income.w1
wide01$mov_income.w3 <- wide01$mov_income.w1
wide01$mov_income.w4 <- wide01$mov_income.w1

# sjmisc::frq(wide01$mov_income)
wide01$mov_median_inc.w1 <- as.numeric(wide01$inc_median.w4-wide01$inc_median.w1)
wide01$mov_median_inc.w2 <- wide01$mov_median_inc.w1
wide01$mov_median_inc.w3 <- wide01$mov_median_inc.w1
wide01$mov_median_inc.w4 <- wide01$mov_median_inc.w1

# sjmisc::frq(as.numeric(wide01$inc05.w4))
# sjmisc::frq(wide01$inc05.w4)
wide01$mov_inc05.w1 <- as.numeric(as.numeric(wide01$inc05.w4)-as.numeric(wide01$inc05.w1))
wide01$mov_inc05.w2 <- wide01$mov_inc05.w1
wide01$mov_inc05.w3 <- wide01$mov_inc05.w1
wide01$mov_inc05.w4 <- wide01$mov_inc05.w1
sjmisc::frq(wide01$mov_inc05.w1); sjPlot::plot_frq(wide01$mov_inc05.w1)

wide01$mov_ess.w1 <- as.numeric(wide01$ess.w4-wide01$ess.w1)
wide01$mov_ess.w2 <- wide01$mov_ess.w1
wide01$mov_ess.w3 <- wide01$mov_ess.w1
wide01$mov_ess.w4 <- wide01$mov_ess.w1
sjmisc::frq(wide01$mov_ess.w1); sjPlot::plot_frq(wide01$mov_ess.w1)

long01<- melt(wide01 %>% 
                # fijar casos con idencuesta >=3 para random slope
              filter(idencuesta %in% ids_filter),
              id.vars = "idencuesta",
              variable.name = "year",
              measure = patterns("^mujer.","^edad.","^educacion.","^ess.","^essfam.",
                                 "^movsubj.","^mov_sub_c.","^moveduc.",
                                 "^income_pc.","^inc05.","^mov_income.","^mov_inc05",
                                 "^mov_median_inc.","^mov_ess.","^mov_educat.",
                                 "^salperger.","^salperobr","^saljusobr.","^saljusger.",
                                 "^gap_perc.","^lngap_perc.","^gap_just.","^lngap_just."),
              value.name = c("mujer","edad","educacion","ess","essfam",
                             "movsubj","mov_sub_c","moveduc",
                             "income_pc","inc05", "mov_income","mov_inc05",
                             "mov_median_inc", "mov_ess","mov_educat",
                             "salperger","salperobr","saljusobr","saljusger",
                             "gap_perc","lngap_perc","gap_just","lngap_just"),
              value.factor = T)


# sjmisc::frq(long01$mov_median_inc)
# sjmisc::frq(long01$mov_inc05)
# sjmisc::frq(long01$mov_educ)
# sjmisc::frq(long01$movsubj)
# sjmisc::frq(long01$mov_sub_c)
# sjmisc::frq(long01$mov_educat)

# #centrado movilidad objetiva
# long01 <- long01 %>% group_by(idencuesta) %>% mutate(mov_educ_cgm = mean(mov_educ,na.rm=T))

#centrado movilidad subjetiva
long01 <- long01 %>% group_by(idencuesta) %>% mutate(mov_subj_mean = mean(movsubj,na.rm=T))
long01$mov_subj_cwc<-long01$movsubj - long01$mov_subj_mean

#centrado movilidad subjetiva categorica
long01$sub_asc<-as.integer(car::recode(long01$mov_sub_c, "'Mov. Asc.'=1;c('Mov. Des.','Estable')=0"))
long01$sub_des<-as.integer(car::recode(long01$mov_sub_c, "'Mov. Des.'=1;c('Mov. Asc.','Estable')=0"))
sjmisc::frq(long01$sub_asc)
sjmisc::frq(long01$sub_des)

long01 <- long01 %>% group_by(idencuesta) %>% mutate(sub_asc_cgm = mean(sub_asc,na.rm=T))

long01$sub_asc_cwc<-long01$sub_asc-long01$sub_asc_cgm
summary(long01$sub_asc_cwc)

long01 <- long01 %>% group_by(idencuesta) %>% mutate(sub_des_cgm = mean(sub_des,na.rm=T))
long01$sub_des_cwc<-long01$sub_des-long01$sub_des_cgm
summary(long01$sub_des_cwc)

# sjmisc::frq(long01$mov_educ)
# sjmisc::frq(long01$movsubj)
# sjmisc::frq(long01$mov_sub_c)
long01$year <- car::recode(long01$year,recodes = "1=2016;2=2017;3=2018;4=2019")
long01b <- long01
long01b <- long01b %>% filter(year %in% c(2016,2017,2018,2019))
table(long01b$year)

long01b <- long01b %>% filter(year %in% c(2016,2017,2018,2019))
long01b$year <- factor(long01b$year,
                       levels = c(2016,2017,2018,2019),
                       labels = c("2016","2017","2018","2019"))

view_df(long01b,show.type = T)
save(long01b,file = "input/data/proc/long01b.RData")
```
