---
title: "Analysis"
date: "`r format(Sys.time(), '%A %d %B %Y %X')`"
output:
  html_document:
    number_sections: true
    toc: true
    toc_float:
        collapsed: false
    toc_depth: 2
    code_folding: "hide"
editor_options:
  chunk_output_type: console
---

```{r remedy01, eval=FALSE, include=FALSE}
rmarkdown::render(input = "production/prod_analysis.Rmd",output_format = "html_document",output_dir = "production/");browseURL(url = "production/prod_analysis.html")
```

```{r remedy02, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,message = FALSE, cache = TRUE,results = "hold")
knitr::opts_knit$set(root.dir = "../")
options(scipen=999)
rm(list=ls())
options(knitr.kable.NA = '')
```

**libraries**
```{r remedy03}
library(dplyr)
library(sjlabelled)
library(sjPlot)
library(stargazer)
library(ggplot2)
library(lme4)
library(mitml) # r2 multinivel
library(corrplot)
```

```{r remedy04}
load(file = "input/data/proc/long01b.RData")
```

## Descriptivos

### Salario percibido por ocupaci칩n


```{r remedy09}
ds.perobr <-
  psych::describeBy(x = long01b$salperobr,
                    group = long01b$year,
                    mat = T) %>% select(group1, n, mean, se, median, min, max) %>% mutate(ocup =
                                                                                            "Obrero")

ds.perger <-
  psych::describeBy(x = long01b$salperger,
                    group = long01b$year,
                    mat = T) %>% select(group1, n, mean, se, median, min, max) %>% mutate(ocup =
                                                                                            "Gerente")
ds.perc <- bind_rows(ds.perobr, ds.perger) %>%
  filter(group1 %in% c(2016:2019))

# salario percibido por ocupacion
ds.perc01 <-
  ggplot(data = ds.perc, aes(
    x = reorder(group1, desc(group1)),
    y = median,
    fill = ocup
  )) +
  geom_bar(position = 'dodge', stat = 'identity') +
  geom_text(aes(
    label = format(median, big.mark = ",", scientific = FALSE),
    y = 0
  ),
  position = position_dodge(0.9),
  hjust = -0.25) +
  theme_bw(base_size = 12) +
  scale_y_continuous(labels = scales::comma) +
  ylab('Salario percibido (mediana)') + xlab('A침os') +
  scale_fill_brewer(palette = "Paired") +
  theme(legend.position = "top") +
  labs(fill = " ") +
  coord_flip()
ds.perc01

ggsave(
  ds.perc01,
  filename = "output/images/ds.perc01.png",
  device = "png",
  width = 30,
  height = 15,
  dpi = "retina",
  units = "cm"
)
```


```{r sal-just-ocup}
# salario justo por ocupacion
ds.jusobr <-
psych::describeBy(x = long01b$saljusobr,
                    group = long01b$year,
                    mat = T) %>% select(group1, n, mean, se, median, min, max) %>%
  mutate(ocup ="Obrero")
ds.jusger <-
  psych::describeBy(x = long01b$saljusger,
                    group = long01b$year,
                    mat = T) %>% select(group1, n, mean, se, median, min, max) %>% 
  mutate(ocup = "Gerente")
ds.just <- bind_rows(ds.jusobr, ds.jusger) %>%
  filter(group1 %in% c(2016:2019))

ds.just01 <-
  ggplot(data = ds.just, aes(
    x = reorder(group1, desc(group1)),
    y = median,
    fill = ocup
  )) +
  geom_bar(position = 'dodge', stat = 'identity') +
  geom_text(aes(
    label = format(median, big.mark = ",", scientific = FALSE),
    y = 0
  ),
  position = position_dodge(0.9),
  hjust = -0.25) +
  theme_bw(base_size = 12) +
  scale_y_continuous(labels = scales::comma) +
  ylab('Salario justo (mediana)') + xlab('A침os') +
  scale_fill_brewer(palette = "Paired") +
  theme(legend.position = "top") +
  labs(fill = " ") +
  coord_flip()
ds.just01

ggsave(
  ds.just01,
  filename = "output/images/ds.just01.png",
  device = "png",
  width = 30,
  height = 15,
  dpi = "retina",
  units = "cm"
)
```

## Univariado

```{r plot-desc-gaps}
ds.gaper<- 
  psych::describeBy(x = long01b$gap_perc,group = long01b$year,mat = T) %>% 
  select(group1,n,mean,se,median,min,max) %>% 
  mutate(brecha="Percibida") %>% 
  filter(group1 %in% c(2016:2019))

ds.gajust<- 
  psych::describeBy(x = long01b$gap_just,group = long01b$year,mat = T) %>% 
  select(group1,n,mean,se,median,min,max) %>% 
  mutate(brecha="Justa") %>% 
  filter(group1 %in% c(2016:2019))  

ds.gaps <- bind_rows(ds.gaper,ds.gajust)

ds.gaps01<-
  ggplot(data=ds.gaps, aes(x=reorder(group1, desc(group1)), y=median, fill=brecha)) +
  geom_bar(position = 'dodge', stat='identity') +
  geom_text(aes(label=format(round(median,digits = 2), big.mark = ",", scientific = FALSE), y=0),position=position_dodge(0.9), hjust=-0.25) +
     theme_bw(base_size = 12) +
     scale_y_continuous(labels = scales::comma) +
     ylab('Brecha salarial (mediana)') + xlab('A침os') +
     scale_fill_brewer(palette="Paired") +
     theme(legend.position="top") +
     labs(fill = " ") +
     coord_flip()
ds.gaps01
ggsave(ds.gaps01,filename = "output/images/ds.gaps01.png",
       device = "png",width = 30,height = 15,dpi = "retina",units = "cm")
```


```{r corr-perc-just}
cormat<- cor(wide01 %>% select(starts_with("lngap_just"),starts_with("lngap_perc")),use = "complete.obs")
p.mat <- cor.mtest(wide01 %>% select(starts_with("lngap_just"),starts_with("lngap_perc")),use = "complete.obs")$p

colnames(cormat) <- c("Just (t1)","Just (t2)","Just (t3)","Just (t4)",
                      "Perc(t1)","Perc (t2)","Perc (t3)","Perc (t4)")

rownames(cormat) <- c("Justa (t1)","Justa (t2)","Justa (t3)","Justa (t4)",
                      "Percibida (t1)","Percibida (t2)","Percibida (t3)","Percibida (t4)")

library(corrplot)
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
png("output/images/cormat01.png", width = 1920, height = 1100,res = "200")
corrplot(cormat, method = "color",
         type = "upper", number.cex = .8,
         addCoef.col = "black", # Add coefficient of correlation
         tl.col = "black", tl.srt = 45, # Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag = FALSE)
dev.off()

sjPlot::sjp.corr(wide01 %>% select(starts_with("lngap_just"),starts_with("lngap_perc")))
```

## Modelos 

```{r mov-educ}
pacman::p_load(dataverse,dplyr,sjlabelled,sjPlot,stargazer,lme4,psych,here,
               ggplot2)
options(scipen=999)
rm(list=ls())
load(file = here::here("input/data/proc/long01b.RData"))

# long01b$year <- as.numeric(long01b$year)

m1 <- "year+movsubj+moveduc+lngap_perc+mujer+edad"
m2 <- "year+mov_sub_c+moveduc+lngap_perc+ mujer+edad"
m3 <- "year+movsubj+mov_educat+lngap_perc+ mujer+edad"
m4 <- "year+mov_sub_c+mov_educat+lngap_perc+ mujer+edad"
m5 <- "year+mov_subj_cwc+mov_subj_mean+moveduc+lngap_perc+mujer+edad"
m6 <- "year+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+ moveduc+lngap_perc+mujer+edad"
m7 <- "year+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+ mov_educat+lngap_perc+mujer+edad"

hipotesis <- c(m1,m2,m3,m4,m5,m6,m7)
# Set the independent variables (IVs)
ivs<- "lngap_just"

# Create the object for each model
models <- list()
for (i in ivs) {
models[[i]] <- paste0(i,"~",hipotesis,"+(1|idencuesta)")  
}

# Estimate the multilevel models
fits <- list()
for (i in ivs) {
  for (z in models[[i]][1:length(hipotesis)]) {
    fits[[z]] <- lme4::lmer(formula = z, data = long01b)
  }
}
fit1 <- fits
# change model names within list
names(fit1) <- paste0(rep(ivs,each=length(hipotesis)),1:length(hipotesis))

omit <- "(Intercept)|(year)|(edad)|(mujer)|(lngap_perc)|(sub_asc_cgm)|(sub_des_cgm)"
texreg::screenreg(l = fit1$lngap_just6, 
                  omit.coef = omit)


custom.coef <- c("Movilidad Educacional (FE)",
                 "Movilidad Subjetiva Ascendente (cwc)",
                 "Movilidad Subjetiva Descendente (cwc)")

lngap_just6<- 
jtools::plot_summs(fit1$lngap_just6,
                   coefs =  c("moveduc","sub_asc_cwc","sub_des_cwc")) +
  labs(title = "Modelo Multinivel Longitudinal - ELSOC",
       caption = paste0("Observaciones = ",nobs(fit1$lngap_just6),
                        ", Individuos = ",length(fit1$lngap_just6@u),
                        ", Incluye controles")) +
  scale_y_discrete(labels=rev(custom.coef))
lngap_just6

ggsave(plot = lngap_just6,
       filename = here::here("output/images/model_elsoc.png"),
       device = "png",
       width = 20,height = 15,
       units = "cm")


```

```{r mov-income}
load(file = "input/data/proc/long01b.RData") #base con na.omit() y att fijos
m16_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educat+mov_income ,data=subset(long01b, year==2016))
m17_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educat+mov_income ,data=subset(long01b, year==2017))
m18_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educat+mov_income ,data=subset(long01b, year==2018))
m19_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educat+mov_income ,data=subset(long01b, year==2019))
m16_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educat+mov_income,data=subset(long01b, year==2016))
m17_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educat+mov_income,data=subset(long01b, year==2017))
m18_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educat+mov_income,data=subset(long01b, year==2018))
m19_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educat+mov_income,data=subset(long01b, year==2019))

texreg::screenreg(l = list(m16_con,m17_con,m18_con,m19_con, 
                           m16_cat,m17_cat,m18_cat,m19_cat
                           ))

#modelos sin centrado
mov_con <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+movsubj+mov_educat+mov_income+lngap_perc+(1|idencuesta),data=long01b)

mov_cat <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_sub_c+mov_educat+mov_income+lngap_perc+(1|idencuesta),data=long01b)

#modelos con centrado
mov_con_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educat+mov_income+lngap_perc+(1|idencuesta),data=long01b)

mov_cat_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+ mov_educat+mov_income+lngap_perc+ (1|idencuesta),data=long01b)

omit <- c("year")
texreg::screenreg(l = list(mov_con,mov_con_cent, 
                           mov_cat,mov_cat_cent), 
                  omit.coef = "(year)|(edad)|(mujer)")
```

```{r mov-median-income}
load(file = "input/data/proc/long01a.RData") #base sin na.omit() y att fijos
load(file = "input/data/proc/long01b.RData") #base con na.omit() y att fijos
m16_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_median_inc ,data=subset(long01b, year==2016))
m17_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_median_inc ,data=subset(long01b, year==2017))
m18_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_median_inc ,data=subset(long01b, year==2018))
m19_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_median_inc ,data=subset(long01b, year==2019))

m16_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_median_inc,data=subset(long01b, year==2016))
m17_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_median_inc,data=subset(long01b, year==2017))
m18_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_median_inc,data=subset(long01b, year==2018))
m19_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_median_inc,data=subset(long01b, year==2019))

texreg::screenreg(l = list(m16_con,m17_con,m18_con,m19_con, 
                           m16_cat,m17_cat,m18_cat,m19_cat
                           ))

#modelos sin centrado
mov_con <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+movsubj+mov_educ+mov_median_inc+lngap_perc+(1|idencuesta),data=long01b)

mov_cat <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_sub_c+mov_educ+mov_median_inc+lngap_perc+(1|idencuesta),data=long01b)

#modelos con centrado
mov_con_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_median_inc+lngap_perc+(1|idencuesta),data=long01b)

mov_cat_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_median_inc+lngap_perc+ (1|idencuesta),data=long01b)

omit <- c("year")
texreg::screenreg(l = list(mov_con,mov_con_cent, 
                           mov_cat,mov_cat_cent), 
                  omit.coef = "(year)|(edad)|(mujer)")
```

```{r mov-quintile-income}
load(file = "input/data/proc/long01a.RData") #base sin na.omit() y att fijos
load(file = "input/data/proc/long01b.RData") #base con na.omit() y att fijos

m16_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_inc05 ,data=subset(long01b, year==2016))
m17_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_inc05 ,data=subset(long01b, year==2017))
m18_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_inc05 ,data=subset(long01b, year==2018))
m19_con <- lm(lngap_just ~ mujer+edad+mov_subj_cwc+mov_subj_mean+mov_educ+mov_inc05 ,data=subset(long01b, year==2019))

m16_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_inc05,data=subset(long01b, year==2016))
m17_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_inc05,data=subset(long01b, year==2017))
m18_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_inc05,data=subset(long01b, year==2018))
m19_cat <- lm(lngap_just ~ mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+mov_educ+mov_inc05,data=subset(long01b, year==2019))

texreg::screenreg(l = list(m16_con,m17_con,m18_con,m19_con, 
                           m16_cat,m17_cat,m18_cat,m19_cat
                           ))

#modelos sin centrado
mov_con <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+movsubj+mov_inc05+lngap_perc+(1|idencuesta),data=long01b)

mov_cat <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_sub_c+mov_inc05+lngap_perc+(1|idencuesta),data=long01b)

#modelos con centrado
mov_con_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_subj_cwc+mov_subj_mean+mov_inc05+lngap_perc+(1|idencuesta),data=long01b)

mov_cat_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+sub_asc_cwc+sub_des_cwc+sub_asc_cgm+sub_des_cgm+ mov_inc05+lngap_perc+ (1|idencuesta),data=long01b)

omit <- c("year")
texreg::screenreg(l = list(mov_con,mov_con_cent, 
                           mov_cat,mov_cat_cent), 
                  omit.coef = "(year)|(edad)|(mujer)")
```

```{r mov-ess}
load(file = "input/data/proc/long01a.RData") #base sin na.omit() y att fijos
load(file = "input/data/proc/long01b.RData") #base con na.omit() y att fijos

m16_con <- lm(lngap_just ~ mujer+edad+mov_ess ,data=subset(long01b, year==2016))
m17_con <- lm(lngap_just ~ mujer+edad+mov_ess ,data=subset(long01b, year==2017))
m18_con <- lm(lngap_just ~ mujer+edad+mov_ess ,data=subset(long01b, year==2018))
m19_con <- lm(lngap_just ~ mujer+edad+mov_ess ,data=subset(long01b, year==2019))

m16_cat <- lm(lngap_just ~ mujer+edad+mov_ess,data=subset(long01b, year==2016))
m17_cat <- lm(lngap_just ~ mujer+edad+mov_ess,data=subset(long01b, year==2017))
m18_cat <- lm(lngap_just ~ mujer+edad+mov_ess,data=subset(long01b, year==2018))
m19_cat <- lm(lngap_just ~ mujer+edad+mov_ess,data=subset(long01b, year==2019))

texreg::screenreg(l = list(m16_con,m17_con,m18_con,m19_con, 
                           m16_cat,m17_cat,m18_cat,m19_cat
                           ))

#modelos sin centrado
mov_con <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_ess+lngap_perc+(1|idencuesta),data=long01b)

mov_cat <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_ess+lngap_perc+(1|idencuesta),data=long01b)

#modelos con centrado
mov_con_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+mov_ess+lngap_perc+(1|idencuesta),data=long01b)

mov_cat_cent <- 
  lme4::lmer(lngap_just ~ year+mujer+edad+ mov_ess+lngap_perc+ (1|idencuesta),data=long01b)

omit <- c("year")
texreg::screenreg(l = list(mov_con,mov_con_cent, 
                           mov_cat,mov_cat_cent), 
                  omit.coef = "(year)|(edad)|(mujer)")
```




